/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nf.clear;

import com.google.inject.Guice;
import com.google.inject.Injector;

import nf.clear.infra.http.HttpServer;
import nf.clear.infra.http.Route;

public class App {

    public static void main(String[] args) {
        Injector injector = Guice.createInjector(new BasicModule());
        var httpServer = injector.getInstance(HttpServer.class);
        var route = injector.getInstance(Route.class);

        route.create(httpServer);
        httpServer.listen(7070);
    }
}
